INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Mr. John', 'Doe', 'john.doe@bolsadeideas.com', '2018-01-02');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Linus', 'Torvalds', 'linus.torvalds@bolsadeideas.com', '2018-01-03');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Ramus', 'Lerdorf', 'rasmus.lerdorf@bolsadeideas.com', '2018-01-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Erich', 'Camma', 'erich.gamma@bolsadeideas.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Richard', 'Helm', 'richard.helm@bolsadeideas.com', '2018-02-10');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Ralph', 'Johnson', 'ralph.johnson@bolsadeideas.com', '2018-02-18');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('John', 'Vlissides', 'john.vlissides@bolsadeideas.com', '2018-02-26');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Dr. James', 'Gosling', 'james.gosling@bolsadeideas.com', '2018-03-03');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Magma', 'Lee', 'ralph.johnson@bolsadeideas.com', '2018-03-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Tornado', 'Roe', 'tornado.roe@bolsadeideas.com', '2018-03-05');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('Jade', 'Doe', 'jade.doe@bolsadeideas.com', '2018-03-06');